### ISSUE TITLE
404 - ng2-facebook-sdk/dist/ng2-facebook-sdk 

### ISSUE THREAD

**Issue by theromie** [zyramedia/ng2-facebook-sdk#49] opened 2017-03-09 12:30 UTC
I am getting 404 error on ng2-facebook-sdk 
in my app.module.ts
import { FacebookService } from "ng2-facebook-sdk/dist/ng2-facebook-sdk";
providers: [FacebookService]

**Comment by ihadeed** [comment] 2017-03-09 20:46
Duplicate of https://github.com/zyramedia/ng2-facebook-sdk/issues/25

**Closed by ihadeed** 2017-03-09 20:46 UTC
